// import { Geist, Geist_Mono, Outfit } from "next/font/google";
import {DM_Sans} from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";
import { twMerge } from "tailwind-merge";
import Header from "./_components/Header";


// const outfit = Outfit({
//     subsets: ["latin"],
// });

const dmSans = DM_Sans({
    subsets: ["latin"],
});

export const metadata = {
    title: "Personal Finance Advisor",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <ClerkProvider>
                <body className={twMerge(dmSans.className, "antialiased")}>
                    {/* <Header/> */}
                    {children}
                    <Toaster position="bottom-right" />                
                </body>
            </ClerkProvider>
        </html>
    );
}
